#!/usr/bin/env bash
#
# Write .env once, with generated database passwords.
#
# The only secrets this stack states are its own MySQL credentials — a database
# container cannot read its own password out of a table it is hosting. Every
# other setting is a row in echo_tbl_Settings, and the NocoDB address comes
# from identity's config volume, so there is nothing else to fill in.
#
# Never overwrites an existing .env: the passwords in it are the ones the
# database volume was initialised with, and regenerating them would lock the
# stack out of its own data. Run it as often as you like.

set -euo pipefail

cd "$(dirname "$0")/.."
ENV_FILE=".env"

if [ -f "$ENV_FILE" ]; then
  echo "[install] $ENV_FILE already exists — leaving it alone."
  echo "[install] Delete it only if you are also discarding the database volume;"
  echo "[install] the passwords in it are what that volume was created with."
  exit 0
fi

gen() { head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 24; }

cat > "$ENV_FILE" <<EOF
# EchoOrchestrator environment — generated by scripts/install.sh
#
# This file carries what the *containers* need, not what the applications need.
# Each Echo app reads its own settings from echo_tbl_Settings in the Echo
# database (EchoDatabase init/009_settings.sql), keyed by sApp.
#
# There is deliberately no NOCODB_* here. EchoWeb reads nothing from NocoDB,
# and EchoService reads identity's /data/config.json from the identity-config
# volume, mounted read-only. Bring identity up and finish its /setup first.

# ── MySQL (EchoDatabase) ─────────────────────────────────────────────────────
# Generated once. The database volume is initialised with these; changing them
# afterwards locks the stack out of its own data.
MYSQL_ROOT_PASSWORD=$(gen)
MYSQL_DATABASE=echo_db
MYSQL_USER=echo_app
MYSQL_PASSWORD=$(gen)

# ── Optional ─────────────────────────────────────────────────────────────────
# Pin the trusted network instead of reading it from IdentityBase. Normally
# left blank: identity owns that row and EchoService reads it.
# IDENTITY_TRUSTED_NETWORK=

# The identity config volume to mount into EchoService, if identity's compose
# project is not named "identity".
# IDENTITY_CONFIG_VOLUME=identity_identity-config
EOF

chmod 600 "$ENV_FILE"
echo "[install] wrote $ENV_FILE with generated database passwords (mode 0600)."
echo "[install] Next: bring up identity and complete its /setup, then"
echo "[install]   docker compose up -d --build"
